"""Describe change6.5.2

Revision ID: 08b28bf0ca93
Revises: abd10dc99064
Create Date: 2025-06-06 00:41:03.421898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08b28bf0ca93'
down_revision: Union[str, None] = 'abd10dc99064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_logs', sa.Column('CEFR', sa.String(length=255), nullable=True))
    op.add_column('learning_logs', sa.Column('daily_caiji', sa.Float(), nullable=True))
    op.create_index(op.f('ix_learning_logs_CEFR'), 'learning_logs', ['CEFR'], unique=False)
    op.alter_column('learning_settings', 'average_caiji',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_settings', 'average_caiji',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_learning_logs_CEFR'), table_name='learning_logs')
    op.drop_column('learning_logs', 'daily_caiji')
    op.drop_column('learning_logs', 'CEFR')
    # ### end Alembic commands ###
