"""Describe change7.18.1

Revision ID: 0b207477b599
Revises: c930dfb97fba
Create Date: 2025-07-18 10:11:32.077243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b207477b599'
down_revision: Union[str, None] = 'c930dfb97fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_phrases', sa.Column('note', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_phrases', 'note')
    # ### end Alembic commands ###
