"""Describe change6.24

Revision ID: 0b411ab4969e
Revises: 6b1bc44786d9
Create Date: 2025-06-24 17:29:40.798855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b411ab4969e'
down_revision: Union[str, None] = '6b1bc44786d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionaries', sa.Column('phonetic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionaries', 'phonetic')
    # ### end Alembic commands ###
