"""Describe change

Revision ID: 2b16e2b39aa7
Revises: 7ed1d2a22b65
Create Date: 2025-06-02 20:12:52.327794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b16e2b39aa7'
down_revision: Union[str, None] = '7ed1d2a22b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_settings', sa.Column('chosed_word_book_id', sa.Integer(), nullable=True))
    op.drop_column('learning_settings', 'chosed_word_book')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_settings', sa.Column('chosed_word_book', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('learning_settings', 'chosed_word_book_id')
    # ### end Alembic commands ###
