"""Describe change6.12

Revision ID: 52276f91730c
Revises: 08b28bf0ca93
Create Date: 2025-06-12 21:53:49.834204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52276f91730c'
down_revision: Union[str, None] = '08b28bf0ca93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_logs', sa.Column('english_title', sa.String(length=255), nullable=True))
    op.add_column('learning_logs', sa.Column('chinese_title', sa.String(length=255), nullable=True))
    op.drop_column('learning_logs', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_logs', sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('learning_logs', 'chinese_title')
    op.drop_column('learning_logs', 'english_title')
    # ### end Alembic commands ###
