"""Describe change

Revision ID: 7ed1d2a22b65
Revises: 94cf0e9f5c58
Create Date: 2025-06-02 19:50:59.317219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed1d2a22b65'
down_revision: Union[str, None] = '94cf0e9f5c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_logs', sa.Column('status', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_learning_logs_status'), 'learning_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_logs_status'), table_name='learning_logs')
    op.drop_column('learning_logs', 'status')
    # ### end Alembic commands ###
