"""Describe change7.6

Revision ID: 7fc7821337eb
Revises: bd5f6852143f
Create Date: 2025-07-06 17:20:04.899070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7fc7821337eb'
down_revision: Union[str, None] = 'bd5f6852143f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_phrases', 'category',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_index(op.f('ix_saved_phrases_user_id'), 'saved_phrases', ['user_id'], unique=False)
    op.drop_column('saved_phrases', 'daily_caiji')
    op.drop_column('saved_phrases', 'appreciation')
    op.drop_column('saved_phrases', 'tag')
    op.drop_column('saved_phrases', 'date')
    op.drop_column('saved_phrases', 'chinese_title')
    op.drop_column('saved_phrases', 'english_title')
    op.drop_column('saved_phrases', 'artical')
    op.drop_column('saved_phrases', 'CEFR')
    op.drop_column('saved_phrases', 'status')
    op.drop_column('saved_phrases', 'outline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_phrases', sa.Column('outline', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('saved_phrases', sa.Column('status', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('saved_phrases', sa.Column('CEFR', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('saved_phrases', sa.Column('artical', mysql.TEXT(), nullable=True))
    op.add_column('saved_phrases', sa.Column('english_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('saved_phrases', sa.Column('chinese_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('saved_phrases', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('saved_phrases', sa.Column('tag', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('saved_phrases', sa.Column('appreciation', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('saved_phrases', sa.Column('daily_caiji', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_saved_phrases_user_id'), table_name='saved_phrases')
    op.alter_column('saved_phrases', 'category',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
