"""Describe change6.25

Revision ID: 865504454a25
Revises: fa581be623ee
Create Date: 2025-06-26 04:10:29.068743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865504454a25'
down_revision: Union[str, None] = 'fa581be623ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_logs', sa.Column('appreciation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_logs', 'appreciation')
    # ### end Alembic commands ###
