"""Describe change6.5.1

Revision ID: abd10dc99064
Revises: f0450044bb6e
Create Date: 2025-06-05 15:40:00.576386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'abd10dc99064'
down_revision: Union[str, None] = 'f0450044bb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_logs', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('learning_logs', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('learning_logs', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('learning_logs', 'outline',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('learning_logs', 'artical',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_logs', 'artical',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('learning_logs', 'outline',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('learning_logs', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('learning_logs', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('learning_logs', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
