"""Create initial tables

Revision ID: b3aeb7b709a5
Revises: c211803c8841
Create Date: 2025-06-01 18:52:35.451875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3aeb7b709a5'
down_revision: Union[str, None] = 'c211803c8841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('phonetic', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_words_phonetic'), 'words', ['phonetic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_phonetic'), table_name='words')
    op.drop_column('words', 'phonetic')
    # ### end Alembic commands ###
