"""Describe change7.6

Revision ID: bd5f6852143f
Revises: 0d7c8ae74abd
Create Date: 2025-07-06 17:18:46.930843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd5f6852143f'
down_revision: Union[str, None] = '0d7c8ae74abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_phrases', sa.Column('explication', sa.String(length=1000), nullable=True))
    op.add_column('saved_phrases', sa.Column('category', sa.String(length=256), nullable=True))
    op.drop_index(op.f('ix_saved_phrases_CEFR'), table_name='saved_phrases')
    op.drop_index(op.f('ix_saved_phrases_status'), table_name='saved_phrases')
    op.drop_index(op.f('ix_saved_phrases_tag'), table_name='saved_phrases')
    op.create_index(op.f('ix_saved_phrases_category'), 'saved_phrases', ['category'], unique=False)
    op.create_index(op.f('ix_saved_phrases_content'), 'saved_phrases', ['content'], unique=False)
    op.create_index(op.f('ix_saved_phrases_user_id'), 'saved_phrases', ['user_id'], unique=False)
    op.drop_column('saved_phrases', 'status')
    op.drop_column('saved_phrases', 'artical')
    op.drop_column('saved_phrases', 'chinese_title')
    op.drop_column('saved_phrases', 'tag')
    op.drop_column('saved_phrases', 'CEFR')
    op.drop_column('saved_phrases', 'daily_caiji')
    op.drop_column('saved_phrases', 'date')
    op.drop_column('saved_phrases', 'appreciation')
    op.drop_column('saved_phrases', 'outline')
    op.drop_column('saved_phrases', 'english_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_phrases', sa.Column('english_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('saved_phrases', sa.Column('outline', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('saved_phrases', sa.Column('appreciation', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('saved_phrases', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('saved_phrases', sa.Column('daily_caiji', mysql.FLOAT(), nullable=True))
    op.add_column('saved_phrases', sa.Column('CEFR', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('saved_phrases', sa.Column('tag', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('saved_phrases', sa.Column('chinese_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('saved_phrases', sa.Column('artical', mysql.TEXT(), nullable=True))
    op.add_column('saved_phrases', sa.Column('status', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_saved_phrases_user_id'), table_name='saved_phrases')
    op.drop_index(op.f('ix_saved_phrases_content'), table_name='saved_phrases')
    op.drop_index(op.f('ix_saved_phrases_category'), table_name='saved_phrases')
    op.create_index(op.f('ix_saved_phrases_tag'), 'saved_phrases', ['tag'], unique=False)
    op.create_index(op.f('ix_saved_phrases_status'), 'saved_phrases', ['status'], unique=False)
    op.create_index(op.f('ix_saved_phrases_CEFR'), 'saved_phrases', ['CEFR'], unique=False)
    op.drop_column('saved_phrases', 'category')
    op.drop_column('saved_phrases', 'explication')
    # ### end Alembic commands ###
