"""Describe change7.18

Revision ID: c930dfb97fba
Revises: fe1107b182aa
Create Date: 2025-07-18 10:09:28.263053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c930dfb97fba'
down_revision: Union[str, None] = 'fe1107b182aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_logs', sa.Column('note', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_logs', 'note')
    # ### end Alembic commands ###
