"""Describe change

Revision ID: f95f1c9e8efb
Revises: 2b16e2b39aa7
Create Date: 2025-06-05 14:30:19.292065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95f1c9e8efb'
down_revision: Union[str, None] = '2b16e2b39aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_logs', sa.Column('tag', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_learning_logs_tag'), 'learning_logs', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_logs_tag'), table_name='learning_logs')
    op.drop_column('learning_logs', 'tag')
    # ### end Alembic commands ###
