"""Describe change

Revision ID: faaf2cd35c34
Revises: 0a31d7fdb084
Create Date: 2025-06-02 04:05:49.127400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faaf2cd35c34'
down_revision: Union[str, None] = '0a31d7fdb084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('membership', sa.Integer(), nullable=True),
    sa.Column('consecutive_learning', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('word_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_word_books_id'), 'word_books', ['id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.String(length=255), nullable=True),
    sa.Column('CEFR', sa.String(length=255), nullable=True),
    sa.Column('phonetic', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_CEFR'), 'words', ['CEFR'], unique=False)
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_phonetic'), 'words', ['phonetic'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=False)
    op.create_table('learning_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('outline', sa.String(length=1024), nullable=False),
    sa.Column('artical', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_logs_id'), 'learning_logs', ['id'], unique=False)
    op.create_table('learning_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chosed_word_book', sa.String(length=255), nullable=True),
    sa.Column('average_caiji', sa.Float(), nullable=True),
    sa.Column('daily_goal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_learning_settings_user_id'), 'learning_settings', ['user_id'], unique=False)
    op.create_table('word_statuss',
    sa.Column('words_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('learning_factor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['words_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('words_id', 'users_id')
    )
    op.create_index(op.f('ix_word_statuss_learning_factor'), 'word_statuss', ['learning_factor'], unique=False)
    op.create_index(op.f('ix_word_statuss_status'), 'word_statuss', ['status'], unique=False)
    op.create_index(op.f('ix_word_statuss_users_id'), 'word_statuss', ['users_id'], unique=False)
    op.create_index(op.f('ix_word_statuss_words_id'), 'word_statuss', ['words_id'], unique=False)
    op.create_table('word_tag_links',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'tag_id')
    )
    op.create_table('word_wordbook_links',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('word_book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_book_id'], ['word_books.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'word_book_id')
    )
    op.create_table('daily_new_word_links',
    sa.Column('learning_log_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learning_log_id'], ['learning_logs.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('learning_log_id', 'word_id')
    )
    op.create_table('daily_review_word_links',
    sa.Column('learning_log_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learning_log_id'], ['learning_logs.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('learning_log_id', 'word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_review_word_links')
    op.drop_table('daily_new_word_links')
    op.drop_table('word_wordbook_links')
    op.drop_table('word_tag_links')
    op.drop_index(op.f('ix_word_statuss_words_id'), table_name='word_statuss')
    op.drop_index(op.f('ix_word_statuss_users_id'), table_name='word_statuss')
    op.drop_index(op.f('ix_word_statuss_status'), table_name='word_statuss')
    op.drop_index(op.f('ix_word_statuss_learning_factor'), table_name='word_statuss')
    op.drop_table('word_statuss')
    op.drop_index(op.f('ix_learning_settings_user_id'), table_name='learning_settings')
    op.drop_table('learning_settings')
    op.drop_index(op.f('ix_learning_logs_id'), table_name='learning_logs')
    op.drop_table('learning_logs')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index(op.f('ix_words_phonetic'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_index(op.f('ix_words_CEFR'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_word_books_id'), table_name='word_books')
    op.drop_table('word_books')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
