"""Describe change7.18

Revision ID: fe1107b182aa
Revises: d84027e1972c
Create Date: 2025-07-18 08:54:32.283807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1107b182aa'
down_revision: Union[str, None] = 'd84027e1972c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_logs', sa.Column('article_difficulty', sa.Integer(), nullable=True))
    op.add_column('learning_logs', sa.Column('words_difficulty', sa.Integer(), nullable=True))
    op.add_column('learning_logs', sa.Column('save', sa.Integer(), nullable=True))
    op.add_column('saved_phrases', sa.Column('log_id', sa.Integer(), nullable=True))
    op.add_column('saved_phrases', sa.Column('appreciation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_phrases', 'appreciation')
    op.drop_column('saved_phrases', 'log_id')
    op.drop_column('learning_logs', 'save')
    op.drop_column('learning_logs', 'words_difficulty')
    op.drop_column('learning_logs', 'article_difficulty')
    # ### end Alembic commands ###
