"""Describe change7.18.2

Revision ID: ff1c4a33f36c
Revises: 0b207477b599
Create Date: 2025-07-18 11:04:30.675733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff1c4a33f36c'
down_revision: Union[str, None] = '0b207477b599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_logs', 'status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_learning_logs_status'), table_name='learning_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_learning_logs_status'), 'learning_logs', ['status'], unique=False)
    op.alter_column('learning_logs', 'status',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
